# ==================
# Project Details
# ==================
name: "dbt_tpch"
require-dbt-version:
- ">=0.13.1"
version: "1.0"
profile: "tpch"

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
clean-targets:
- "target"
- "dbt_modules"
model-paths:
- "models"
- "prophecy-sources"
analysis-paths:
- "analysis"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  max_ship_date: '''1998-12-01'''

# ==================
# Model Configs
# ==================
models:
  dbt_tpch:
    base:
      schema: "base"
    ods:
      schema: "ods"
    vars:
      max_ship_date: "'1998-12-01'"
    wh:
      schema: "wh"

# ============
# Misc
# ============
quoting:
  database: false
  schema: false
  identifier: false
